max_length: 1000
k_fold: 5

file_path:
  op_path: /home/username/plc_test/dataset/openplc/op_file.pkl
  root_path: /home/username/plc_test/dataset/openplc_dataset
  save_path: /home/username/plc_test/dataset/openplc_dataset

cache:
  read_op: False
  read_cache: False
  